// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLnQo10z47LMcq7CoA5xuStJgSdVspeAI',
    appId: '1:193908568505:web:5271080988b6dee04b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    authDomain: 'trippidy-ee0d4.firebaseapp.com',
    storageBucket: 'trippidy-ee0d4.appspot.com',
    measurementId: 'G-XC0FY6GH7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OimQZx9VlpHUTU4EWTZJfEh19gzFr6w',
    appId: '1:193908568505:android:f57695ab7e4ec7224b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    storageBucket: 'trippidy-ee0d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMqJvFWZufEWtfvl-tucdhKHMCPnvCkE',
    appId: '1:193908568505:ios:33696f5027e1a3094b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    storageBucket: 'trippidy-ee0d4.appspot.com',
    androidClientId: '193908568505-rsvth1g49kj0dni6hr9dim1n791kobon.apps.googleusercontent.com',
    iosClientId: '193908568505-92sg4ignbmc54uklne036ansmupaik9b.apps.googleusercontent.com',
    iosBundleId: 'dev.rexie.trippidy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMqJvFWZufEWtfvl-tucdhKHMCPnvCkE',
    appId: '1:193908568505:ios:33696f5027e1a3094b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    storageBucket: 'trippidy-ee0d4.appspot.com',
    androidClientId: '193908568505-rsvth1g49kj0dni6hr9dim1n791kobon.apps.googleusercontent.com',
    iosClientId: '193908568505-92sg4ignbmc54uklne036ansmupaik9b.apps.googleusercontent.com',
    iosBundleId: 'dev.rexie.trippidy',
  );
}
