// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIoIEUib_6sXTKqce5Xh_cuQ4F2XTLeQw',
    appId: '1:193908568505:web:f7a9370c4cd828524b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    authDomain: 'trippidy-ee0d4.firebaseapp.com',
    storageBucket: 'trippidy-ee0d4.appspot.com',
    measurementId: 'G-LNPCEQ20CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0OimQZx9VlpHUTU4EWTZJfEh19gzFr6w',
    appId: '1:193908568505:android:0650682df867c1894b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    storageBucket: 'trippidy-ee0d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqMqJvFWZufEWtfvl-tucdhKHMCPnvCkE',
    appId: '1:193908568505:ios:27b5912c2f37877e4b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    storageBucket: 'trippidy-ee0d4.appspot.com',
    iosClientId: '193908568505-am1j56fp7sa7g7lqgrqr9aleqjbk67tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.trippidy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqMqJvFWZufEWtfvl-tucdhKHMCPnvCkE',
    appId: '1:193908568505:ios:27b5912c2f37877e4b8668',
    messagingSenderId: '193908568505',
    projectId: 'trippidy-ee0d4',
    storageBucket: 'trippidy-ee0d4.appspot.com',
    iosClientId: '193908568505-am1j56fp7sa7g7lqgrqr9aleqjbk67tn.apps.googleusercontent.com',
    iosBundleId: 'com.example.trippidy',
  );
}
